version: '3'

services:
  app:
    platform: linux/x86_64
    image: ${IMAGE_NAME}
    ports:
      - "${PORT:-8000}:8888"
    restart: always
    container_name: "${CONTAINER_NAME}"


# version: '3.8'

# services:
#   proxy:
#     build: .
#     ports:
#       - "8888:8888"
#     restart: always


