version: '3'

services:
  squid:
    build: .
    ports:
      - "8889:8889"
    volumes:
      - ./squid.conf:/etc/squid/squid.conf
      - ./session_timeout.py:/usr/local/bin/session_timeout.py
    restart: always
